// Code generated by Slice Machine. DO NOT EDIT.

import DistributorLogin from "./DistributorLogin/index.svelte";
import HomePageAnim from "./HomePageAnim/index.svelte";
import ImageRow from "./ImageRow/index.svelte";
import RichText from "./RichText/index.svelte";
import ScreenWidthMedia from "./ScreenWidthMedia/index.svelte";
import TwoCol from "./TwoCol/index.svelte";

export const components = {
  distributor_login: DistributorLogin,
  home_page_anim: HomePageAnim,
  image_row: ImageRow,
  rich_text: RichText,
  screen_width_video: ScreenWidthMedia,
  two_col: TwoCol,
};
