// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type PageDocumentDataSlicesSlice =
  | HomeHeroSlice
  | DistributorLoginSlice
  | ScreenWidthVideoSlice
  | TwoColSlice
  | ImageRowSlice
  | HomePageAnimSlice
  | RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * default background field in *Page*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: light_blue
   * - **API ID Path**: page.default_background
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  default_background: prismic.SelectField<
    "light_blue" | "pink" | "dark_blue" | "teal",
    "filled"
  >;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *resourceHubCategory → headers*
 */
export interface ResourceHubCategoryDocumentDataHeadersItem {
  /**
   * name field in *resourceHubCategory → headers*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: resource_hub_category.headers[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * general field in *resourceHubCategory → headers*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: resource_hub_category.headers[].general
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  general: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * documents field in *resourceHubCategory → headers*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: resource_hub_category.headers[].distributor_documents
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  distributor_documents: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * papers  field in *resourceHubCategory → headers*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: resource_hub_category.headers[].white_papers
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  white_papers: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * videos field in *resourceHubCategory → headers*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: resource_hub_category.headers[].videos
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  videos: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Content for resourceHubCategory documents
 */
interface ResourceHubCategoryDocumentData {
  /**
   * name field in *resourceHubCategory*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: resource_hub_category.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * image field in *resourceHubCategory*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: resource_hub_category.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * headers field in *resourceHubCategory*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: resource_hub_category.headers[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  headers: prismic.GroupField<
    Simplify<ResourceHubCategoryDocumentDataHeadersItem>
  >;
}

/**
 * resourceHubCategory document from Prismic
 *
 * - **API ID**: `resource_hub_category`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ResourceHubCategoryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ResourceHubCategoryDocumentData>,
    "resource_hub_category",
    Lang
  >;

type SurgicalGraftsDocumentDataSlicesSlice =
  | TwoColSlice
  | HomePageAnimSlice
  | ImageRowSlice
  | ScreenWidthVideoSlice
  | RichTextSlice;

/**
 * Content for surgical grafts documents
 */
interface SurgicalGraftsDocumentData {
  /**
   * default background field in *surgical grafts*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: light_blue
   * - **API ID Path**: surgical_grafts.default_background
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  default_background: prismic.SelectField<
    "light_blue" | "pink" | "dark_blue" | "teal",
    "filled"
  >;

  /**
   * Slice Zone field in *surgical grafts*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: surgical_grafts.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<SurgicalGraftsDocumentDataSlicesSlice> /**
   * Meta Title field in *surgical grafts*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: surgical_grafts.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *surgical grafts*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: surgical_grafts.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *surgical grafts*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: surgical_grafts.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * surgical grafts document from Prismic
 *
 * - **API ID**: `surgical_grafts`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SurgicalGraftsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SurgicalGraftsDocumentData>,
    "surgical_grafts",
    Lang
  >;

export type AllDocumentTypes =
  | PageDocument
  | ResourceHubCategoryDocument
  | SurgicalGraftsDocument;

/**
 * Primary content in *DistributorLogin → Default → Primary*
 */
export interface DistributorLoginSliceDefaultPrimary {
  /**
   * vertical padding field in *DistributorLogin → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 0
   * - **API ID Path**: distributor_login.default.primary.vertical_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  vertical_padding: prismic.SelectField<"0" | "5" | "10" | "20", "filled">;
}

/**
 * Default variation for DistributorLogin Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DistributorLoginSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DistributorLoginSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *DistributorLogin*
 */
type DistributorLoginSliceVariation = DistributorLoginSliceDefault;

/**
 * DistributorLogin Shared Slice
 *
 * - **API ID**: `distributor_login`
 * - **Description**: DistributorLogin
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DistributorLoginSlice = prismic.SharedSlice<
  "distributor_login",
  DistributorLoginSliceVariation
>;

/**
 * Primary content in *HomeHero → Default → Primary*
 */
export interface HomeHeroSliceDefaultPrimary {
  /**
   * placeholder Image field in *HomeHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero.default.primary.placeholder_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  placeholder_image: prismic.ImageField<never>;

  /**
   * vimeo Id field in *HomeHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero.default.primary.vimeo_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  vimeo_id: prismic.KeyTextField;

  /**
   * show scroll arrow field in *HomeHero → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: home_hero.default.primary.show_scroll_arrow
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_scroll_arrow: prismic.BooleanField;

  /**
   * text field in *HomeHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * button field in *HomeHero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero.default.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for HomeHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HomeHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomeHero*
 */
type HomeHeroSliceVariation = HomeHeroSliceDefault;

/**
 * HomeHero Shared Slice
 *
 * - **API ID**: `home_hero`
 * - **Description**: HomeHero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HomeHeroSlice = prismic.SharedSlice<
  "home_hero",
  HomeHeroSliceVariation
>;

/**
 * Default variation for HomePageAnim Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HomePageAnimSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *HomePageAnim*
 */
type HomePageAnimSliceVariation = HomePageAnimSliceDefault;

/**
 * HomePageAnim Shared Slice
 *
 * - **API ID**: `home_page_anim`
 * - **Description**: HomePageAnim
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HomePageAnimSlice = prismic.SharedSlice<
  "home_page_anim",
  HomePageAnimSliceVariation
>;

/**
 * Item in *ImageRow → Default → Primary → images*
 */
export interface ImageRowSliceDefaultPrimaryImagesItem {
  /**
   * image field in *ImageRow → Default → Primary → images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_row.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * label field in *ImageRow → Default → Primary → images*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_row.default.primary.images[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;
}

/**
 * Primary content in *ImageRow → Default → Primary*
 */
export interface ImageRowSliceDefaultPrimary {
  /**
   * images field in *ImageRow → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: image_row.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  images: prismic.GroupField<Simplify<ImageRowSliceDefaultPrimaryImagesItem>>;

  /**
   * vertical padding field in *ImageRow → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 0
   * - **API ID Path**: image_row.default.primary.vertical_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  vertical_padding: prismic.SelectField<"0" | "5" | "10" | "20", "filled">;
}

/**
 * Default variation for ImageRow Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageRowSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageRowSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageRow*
 */
type ImageRowSliceVariation = ImageRowSliceDefault;

/**
 * ImageRow Shared Slice
 *
 * - **API ID**: `image_row`
 * - **Description**: ImageRow
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageRowSlice = prismic.SharedSlice<
  "image_row",
  ImageRowSliceVariation
>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * text field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * button field in *RichText → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.default.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary"
  >;

  /**
   * show scroll arrow field in *RichText → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: rich_text.default.primary.show_scroll_arrow
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_scroll_arrow: prismic.BooleanField;

  /**
   * vertical padding field in *RichText → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 0
   * - **API ID Path**: rich_text.default.primary.vertical_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  vertical_padding: prismic.SelectField<
    "0" | "5" | "10" | "20" | "40",
    "filled"
  >;

  /**
   * max width field in *RichText → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: full
   * - **API ID Path**: rich_text.default.primary.max_width
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  max_width: prismic.SelectField<"full" | "limited", "filled">;

  /**
   * float field in *RichText → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: rich_text.default.primary.floatCenter
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  floatCenter: prismic.BooleanField;

  /**
   * button two field in *RichText → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.default.primary.button_two
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_two: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary"
  >;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Primary content in *ScreenWidthMedia → Default → Primary*
 */
export interface ScreenWidthVideoSliceDefaultPrimary {
  /**
   * vimeo Id field in *ScreenWidthMedia → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: screen_width_video.default.primary.vimeo_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  vimeo_id: prismic.KeyTextField;

  /**
   * placeholder Image field in *ScreenWidthMedia → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: screen_width_video.default.primary.placeholder_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  placeholder_image: prismic.ImageField<never>;

  /**
   * text field in *ScreenWidthMedia → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: screen_width_video.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * button field in *ScreenWidthMedia → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: screen_width_video.default.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary"
  >;

  /**
   * text float field in *ScreenWidthMedia → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: center
   * - **API ID Path**: screen_width_video.default.primary.text_float
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  text_float: prismic.SelectField<"center" | "bottom", "filled">;

  /**
   * height field in *ScreenWidthMedia → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: screen
   * - **API ID Path**: screen_width_video.default.primary.height
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  height: prismic.SelectField<"screen" | "half screen", "filled">;

  /**
   * darken image field in *ScreenWidthMedia → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: screen_width_video.default.primary.darken
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  darken: prismic.BooleanField;

  /**
   * max width field in *ScreenWidthMedia → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: full
   * - **API ID Path**: screen_width_video.default.primary.max_width
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  max_width: prismic.SelectField<"full" | "limited", "filled">;

  /**
   * show scroll arrow field in *ScreenWidthMedia → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: screen_width_video.default.primary.show_scroll_arrow
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_scroll_arrow: prismic.BooleanField;

  /**
   * button two field in *ScreenWidthMedia → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: screen_width_video.default.primary.button_two
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_two: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary"
  >;
}

/**
 * Default variation for ScreenWidthMedia Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ScreenWidthVideoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ScreenWidthVideoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ScreenWidthMedia*
 */
type ScreenWidthVideoSliceVariation = ScreenWidthVideoSliceDefault;

/**
 * ScreenWidthMedia Shared Slice
 *
 * - **API ID**: `screen_width_video`
 * - **Description**: ScreenWidthVideo
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ScreenWidthVideoSlice = prismic.SharedSlice<
  "screen_width_video",
  ScreenWidthVideoSliceVariation
>;

/**
 * Item in *TwoCol → imageTableText → Primary → products*
 */
export interface TwoColSliceImageTableTextPrimaryProductsItem {
  /**
   * description field in *TwoCol → imageTableText → Primary → products*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_col.imageTableText.primary.products[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * size one field in *TwoCol → imageTableText → Primary → products*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_col.imageTableText.primary.products[].size_one
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  size_one: prismic.KeyTextField;

  /**
   * size_two field in *TwoCol → imageTableText → Primary → products*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_col.imageTableText.primary.products[].size_two
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  size_two: prismic.KeyTextField;

  /**
   * product number field in *TwoCol → imageTableText → Primary → products*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_col.imageTableText.primary.products[].product_number
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  product_number: prismic.KeyTextField;
}

/**
 * Item in *TwoCol → tableText → Primary → products*
 */
export interface TwoColSliceTableTextPrimaryProductsItem {
  /**
   * description field in *TwoCol → tableText → Primary → products*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_col.tableText.primary.products[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * size one field in *TwoCol → tableText → Primary → products*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_col.tableText.primary.products[].size_one
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  size_one: prismic.KeyTextField;

  /**
   * size_two field in *TwoCol → tableText → Primary → products*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_col.tableText.primary.products[].size_two
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  size_two: prismic.KeyTextField;

  /**
   * product number field in *TwoCol → tableText → Primary → products*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_col.tableText.primary.products[].product_number
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  product_number: prismic.KeyTextField;
}

/**
 * Primary content in *TwoCol → media text → Primary*
 */
export interface TwoColSliceDefaultPrimary {
  /**
   * image field in *TwoCol → media text → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: two_col.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * image aspect field in *TwoCol → media text → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: square
   * - **API ID Path**: two_col.default.primary.image_aspect
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  image_aspect: prismic.SelectField<
    "square" | "4:3" | "16:9" | "3:4" | "9:16",
    "filled"
  >;

  /**
   * text field in *TwoCol → media text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_col.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * button field in *TwoCol → media text → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: two_col.default.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary"
  >;

  /**
   * button two field in *TwoCol → media text → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: two_col.default.primary.button_two
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_two: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary"
  >;

  /**
   * order field in *TwoCol → media text → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: two_col.default.primary.isMediaFirst
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  isMediaFirst: prismic.BooleanField;

  /**
   * border top field in *TwoCol → media text → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: two_col.default.primary.showTopBorder
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  showTopBorder: prismic.BooleanField;

  /**
   * vimeo Id field in *TwoCol → media text → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_col.default.primary.vimeo_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  vimeo_id: prismic.KeyTextField;

  /**
   * vertical padding field in *TwoCol → media text → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 0
   * - **API ID Path**: two_col.default.primary.vertical_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  vertical_padding: prismic.SelectField<"0" | "5" | "10" | "20", "filled">;
}

/**
 * media text variation for TwoCol Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TwoColSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TwoColSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *TwoCol → Contact Form → Primary*
 */
export interface TwoColSliceContactFormPrimary {
  /**
   * text field in *TwoCol → Contact Form → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_col.contactForm.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * vertical padding field in *TwoCol → Contact Form → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 0
   * - **API ID Path**: two_col.contactForm.primary.vertical_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  vertical_padding: prismic.SelectField<"0" | "5" | "10" | "20", "filled">;
}

/**
 * Contact Form variation for TwoCol Slice
 *
 * - **API ID**: `contactForm`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TwoColSliceContactForm = prismic.SharedSliceVariation<
  "contactForm",
  Simplify<TwoColSliceContactFormPrimary>,
  never
>;

/**
 * Primary content in *TwoCol → imageTableText → Primary*
 */
export interface TwoColSliceImageTableTextPrimary {
  /**
   * image field in *TwoCol → imageTableText → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: two_col.imageTableText.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * image aspect field in *TwoCol → imageTableText → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: square
   * - **API ID Path**: two_col.imageTableText.primary.image_aspect
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  image_aspect: prismic.SelectField<
    "square" | "4:3" | "16:9" | "3:4" | "9:16",
    "filled"
  >;

  /**
   * text field in *TwoCol → imageTableText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_col.imageTableText.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * button field in *TwoCol → imageTableText → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: two_col.imageTableText.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary"
  >;

  /**
   * button two field in *TwoCol → imageTableText → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: two_col.imageTableText.primary.button_two
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_two: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary"
  >;

  /**
   * order field in *TwoCol → imageTableText → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: two_col.imageTableText.primary.isMediaFirst
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  isMediaFirst: prismic.BooleanField;

  /**
   * border top field in *TwoCol → imageTableText → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: two_col.imageTableText.primary.showTopBorder
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  showTopBorder: prismic.BooleanField;

  /**
   * vimeo Id field in *TwoCol → imageTableText → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_col.imageTableText.primary.vimeo_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  vimeo_id: prismic.KeyTextField;

  /**
   * vertical padding field in *TwoCol → imageTableText → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 0
   * - **API ID Path**: two_col.imageTableText.primary.vertical_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  vertical_padding: prismic.SelectField<"0" | "5" | "10" | "20", "filled">;

  /**
   * col one label field in *TwoCol → imageTableText → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: default is description
   * - **API ID Path**: two_col.imageTableText.primary.col_one_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  col_one_label: prismic.KeyTextField;

  /**
   * col two label field in *TwoCol → imageTableText → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: if present: default is size
   * - **API ID Path**: two_col.imageTableText.primary.col_two_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  col_two_label: prismic.KeyTextField;

  /**
   * col three label field in *TwoCol → imageTableText → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: if present: default is size
   * - **API ID Path**: two_col.imageTableText.primary.col_three_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  col_three_label: prismic.KeyTextField;

  /**
   * last col label field in *TwoCol → imageTableText → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: default is part number
   * - **API ID Path**: two_col.imageTableText.primary.last_col_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  last_col_label: prismic.KeyTextField;

  /**
   * table column field in *TwoCol → imageTableText → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: desc & #, no sizes
   * - **API ID Path**: two_col.imageTableText.primary.table_column
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  table_column: prismic.SelectField<
    | "desc & #, no sizes"
    | "desc and one size and #"
    | "desc and two sizes and #",
    "filled"
  >;

  /**
   * products field in *TwoCol → imageTableText → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: two_col.imageTableText.primary.products[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  products: prismic.GroupField<
    Simplify<TwoColSliceImageTableTextPrimaryProductsItem>
  >;
}

/**
 * imageTableText variation for TwoCol Slice
 *
 * - **API ID**: `imageTableText`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TwoColSliceImageTableText = prismic.SharedSliceVariation<
  "imageTableText",
  Simplify<TwoColSliceImageTableTextPrimary>,
  never
>;

/**
 * Primary content in *TwoCol → tableText → Primary*
 */
export interface TwoColSliceTableTextPrimary {
  /**
   * text field in *TwoCol → tableText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_col.tableText.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * button field in *TwoCol → tableText → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: two_col.tableText.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary"
  >;

  /**
   * button two field in *TwoCol → tableText → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: two_col.tableText.primary.button_two
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_two: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary"
  >;

  /**
   * order field in *TwoCol → tableText → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: two_col.tableText.primary.isTableFirst
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  isTableFirst: prismic.BooleanField;

  /**
   * border top field in *TwoCol → tableText → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: two_col.tableText.primary.showTopBorder
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  showTopBorder: prismic.BooleanField;

  /**
   * vertical padding field in *TwoCol → tableText → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 0
   * - **API ID Path**: two_col.tableText.primary.vertical_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  vertical_padding: prismic.SelectField<"0" | "5" | "10" | "20", "filled">;

  /**
   * table column field in *TwoCol → tableText → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: desc & #, no sizes
   * - **API ID Path**: two_col.tableText.primary.table_column
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  table_column: prismic.SelectField<
    | "desc & #, no sizes"
    | "desc and one size and #"
    | "desc and two sizes and #",
    "filled"
  >;

  /**
   * col one label field in *TwoCol → tableText → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: default is description
   * - **API ID Path**: two_col.tableText.primary.col_one_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  col_one_label: prismic.KeyTextField;

  /**
   * col two label field in *TwoCol → tableText → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: if present: default is size
   * - **API ID Path**: two_col.tableText.primary.col_two_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  col_two_label: prismic.KeyTextField;

  /**
   * col three label field in *TwoCol → tableText → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: if present: default is size
   * - **API ID Path**: two_col.tableText.primary.col_three_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  col_three_label: prismic.KeyTextField;

  /**
   * last col label field in *TwoCol → tableText → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: default is part number
   * - **API ID Path**: two_col.tableText.primary.last_col_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  last_col_label: prismic.KeyTextField;

  /**
   * products field in *TwoCol → tableText → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: two_col.tableText.primary.products[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  products: prismic.GroupField<
    Simplify<TwoColSliceTableTextPrimaryProductsItem>
  >;
}

/**
 * tableText variation for TwoCol Slice
 *
 * - **API ID**: `tableText`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TwoColSliceTableText = prismic.SharedSliceVariation<
  "tableText",
  Simplify<TwoColSliceTableTextPrimary>,
  never
>;

/**
 * Slice variation for *TwoCol*
 */
type TwoColSliceVariation =
  | TwoColSliceDefault
  | TwoColSliceContactForm
  | TwoColSliceImageTableText
  | TwoColSliceTableText;

/**
 * TwoCol Shared Slice
 *
 * - **API ID**: `two_col`
 * - **Description**: TwoCol
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TwoColSlice = prismic.SharedSlice<"two_col", TwoColSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ResourceHubCategoryDocument,
      ResourceHubCategoryDocumentData,
      ResourceHubCategoryDocumentDataHeadersItem,
      SurgicalGraftsDocument,
      SurgicalGraftsDocumentData,
      SurgicalGraftsDocumentDataSlicesSlice,
      AllDocumentTypes,
      DistributorLoginSlice,
      DistributorLoginSliceDefaultPrimary,
      DistributorLoginSliceVariation,
      DistributorLoginSliceDefault,
      HomeHeroSlice,
      HomeHeroSliceDefaultPrimary,
      HomeHeroSliceVariation,
      HomeHeroSliceDefault,
      HomePageAnimSlice,
      HomePageAnimSliceVariation,
      HomePageAnimSliceDefault,
      ImageRowSlice,
      ImageRowSliceDefaultPrimaryImagesItem,
      ImageRowSliceDefaultPrimary,
      ImageRowSliceVariation,
      ImageRowSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      ScreenWidthVideoSlice,
      ScreenWidthVideoSliceDefaultPrimary,
      ScreenWidthVideoSliceVariation,
      ScreenWidthVideoSliceDefault,
      TwoColSlice,
      TwoColSliceDefaultPrimary,
      TwoColSliceContactFormPrimary,
      TwoColSliceImageTableTextPrimaryProductsItem,
      TwoColSliceImageTableTextPrimary,
      TwoColSliceTableTextPrimaryProductsItem,
      TwoColSliceTableTextPrimary,
      TwoColSliceVariation,
      TwoColSliceDefault,
      TwoColSliceContactForm,
      TwoColSliceImageTableText,
      TwoColSliceTableText,
    };
  }
}
