// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type PageDocumentDataSlicesSlice =
  | ScreenWidthVideoSlice
  | TwoColSlice
  | ImageRowSlice
  | HomePageAnimSlice
  | RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type SurgicalGraftsDocumentDataSlicesSlice =
  | TwoColSlice
  | HomePageAnimSlice
  | ImageRowSlice
  | ScreenWidthVideoSlice
  | RichTextSlice;

/**
 * Content for surgical grafts documents
 */
interface SurgicalGraftsDocumentData {
  /**
   * Slice Zone field in *surgical grafts*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: surgical_grafts.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<SurgicalGraftsDocumentDataSlicesSlice> /**
   * Meta Title field in *surgical grafts*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: surgical_grafts.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *surgical grafts*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: surgical_grafts.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *surgical grafts*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: surgical_grafts.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * surgical grafts document from Prismic
 *
 * - **API ID**: `surgical_grafts`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SurgicalGraftsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SurgicalGraftsDocumentData>,
    "surgical_grafts",
    Lang
  >;

export type AllDocumentTypes = PageDocument | SurgicalGraftsDocument;

/**
 * Default variation for HomePageAnim Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HomePageAnimSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *HomePageAnim*
 */
type HomePageAnimSliceVariation = HomePageAnimSliceDefault;

/**
 * HomePageAnim Shared Slice
 *
 * - **API ID**: `home_page_anim`
 * - **Description**: HomePageAnim
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HomePageAnimSlice = prismic.SharedSlice<
  "home_page_anim",
  HomePageAnimSliceVariation
>;

/**
 * Item in *ImageRow → Default → Primary → images*
 */
export interface ImageRowSliceDefaultPrimaryImagesItem {
  /**
   * image field in *ImageRow → Default → Primary → images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_row.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * label field in *ImageRow → Default → Primary → images*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_row.default.primary.images[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;
}

/**
 * Primary content in *ImageRow → Default → Primary*
 */
export interface ImageRowSliceDefaultPrimary {
  /**
   * images field in *ImageRow → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: image_row.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  images: prismic.GroupField<Simplify<ImageRowSliceDefaultPrimaryImagesItem>>;
}

/**
 * Default variation for ImageRow Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageRowSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageRowSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageRow*
 */
type ImageRowSliceVariation = ImageRowSliceDefault;

/**
 * ImageRow Shared Slice
 *
 * - **API ID**: `image_row`
 * - **Description**: ImageRow
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageRowSlice = prismic.SharedSlice<
  "image_row",
  ImageRowSliceVariation
>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * text field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * button field in *RichText → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.default.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary"
  >;

  /**
   * show scroll arrow field in *RichText → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: rich_text.default.primary.show_scroll_arrow
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_scroll_arrow: prismic.BooleanField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Primary content in *ScreenWidthMedia → Default → Primary*
 */
export interface ScreenWidthVideoSliceDefaultPrimary {
  /**
   * vimeo Id field in *ScreenWidthMedia → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: screen_width_video.default.primary.vimeo_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  vimeo_id: prismic.KeyTextField;

  /**
   * placeholder Image field in *ScreenWidthMedia → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: screen_width_video.default.primary.placeholder_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  placeholder_image: prismic.ImageField<never>;

  /**
   * centered text field in *ScreenWidthMedia → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: screen_width_video.default.primary.centered_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  centered_text: prismic.RichTextField;

  /**
   * button one field in *ScreenWidthMedia → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: screen_width_video.default.primary.button_one
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_one: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary"
  >;

  /**
   * text float field in *ScreenWidthMedia → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: center
   * - **API ID Path**: screen_width_video.default.primary.text_float
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  text_float: prismic.SelectField<"center" | "bottom", "filled">;

  /**
   * height field in *ScreenWidthMedia → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: screen
   * - **API ID Path**: screen_width_video.default.primary.height
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  height: prismic.SelectField<"screen" | "half screen", "filled">;
}

/**
 * Default variation for ScreenWidthMedia Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ScreenWidthVideoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ScreenWidthVideoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ScreenWidthMedia*
 */
type ScreenWidthVideoSliceVariation = ScreenWidthVideoSliceDefault;

/**
 * ScreenWidthMedia Shared Slice
 *
 * - **API ID**: `screen_width_video`
 * - **Description**: ScreenWidthVideo
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ScreenWidthVideoSlice = prismic.SharedSlice<
  "screen_width_video",
  ScreenWidthVideoSliceVariation
>;

/**
 * Primary content in *TwoCol → image text → Primary*
 */
export interface TwoColSliceDefaultPrimary {
  /**
   * image field in *TwoCol → image text → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: two_col.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * image aspect field in *TwoCol → image text → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: square
   * - **API ID Path**: two_col.default.primary.image_aspect
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  image_aspect: prismic.SelectField<
    "square" | "4:3" | "16:9" | "3:4" | "9:16",
    "filled"
  >;

  /**
   * text field in *TwoCol → image text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_col.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * button field in *TwoCol → image text → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: two_col.default.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary"
  >;
}

/**
 * image text variation for TwoCol Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TwoColSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TwoColSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *TwoCol → Contact Form → Primary*
 */
export interface TwoColSliceContactFormPrimary {
  /**
   * text field in *TwoCol → Contact Form → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_col.contactForm.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Contact Form variation for TwoCol Slice
 *
 * - **API ID**: `contactForm`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TwoColSliceContactForm = prismic.SharedSliceVariation<
  "contactForm",
  Simplify<TwoColSliceContactFormPrimary>,
  never
>;

/**
 * Slice variation for *TwoCol*
 */
type TwoColSliceVariation = TwoColSliceDefault | TwoColSliceContactForm;

/**
 * TwoCol Shared Slice
 *
 * - **API ID**: `two_col`
 * - **Description**: TwoCol
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TwoColSlice = prismic.SharedSlice<"two_col", TwoColSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SurgicalGraftsDocument,
      SurgicalGraftsDocumentData,
      SurgicalGraftsDocumentDataSlicesSlice,
      AllDocumentTypes,
      HomePageAnimSlice,
      HomePageAnimSliceVariation,
      HomePageAnimSliceDefault,
      ImageRowSlice,
      ImageRowSliceDefaultPrimaryImagesItem,
      ImageRowSliceDefaultPrimary,
      ImageRowSliceVariation,
      ImageRowSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      ScreenWidthVideoSlice,
      ScreenWidthVideoSliceDefaultPrimary,
      ScreenWidthVideoSliceVariation,
      ScreenWidthVideoSliceDefault,
      TwoColSlice,
      TwoColSliceDefaultPrimary,
      TwoColSliceContactFormPrimary,
      TwoColSliceVariation,
      TwoColSliceDefault,
      TwoColSliceContactForm,
    };
  }
}
